### ISSUE TITLE
Sort option is not working

### ISSUE THREAD

**Issue by bonkhand** [econia-labs/emojicoin-dot-fun#426]
![Sort option](https://github.com/user-attachments/assets/f85c944b-af44-4fde-a062-bdb5f5e9b2f0)
Sort option on emojicoin.fun is not working

**Comment by bonkhand** [comment]
It remains bump order

**Comment by xbtmatt** [comment]
Thank you for filing this! We are merging a fix right now for this: #430

**Comment by bonkhand** [comment]
I'm happy to contribute.
