### ISSUE TITLE
All time volume display issue.

### ISSUE THREAD

**Issue by bonkhand** [econia-labs/emojicoin-dot-fun#442]
![image](https://github.com/user-attachments/assets/0357acd5-9bb1-4e77-8646-394f63ad0a8c)

Hey guys,

Click on sort button and select the all time volume option, then we can see coins are getting sorted based on all time volume.

But it's not showing all time volume of each emojicoins, it's showing 24 hours volume.

Please check the attachment, for more details

**Comment by alnoki** [comment]
@bonkhand thank you for filing this issue, we are working on a fix

**Comment by bonkhand** [comment]
It was such a quick response 😍😍😍
